let lessons = [
  {
    id: 1,
    subject: "Swimming",
    location: "London",
    price: 110,
    spaces: 5,
    ratings: 5,
    images: "images/swimming.jpeg",
  },
  {
    id: 2,
    subject: "Football Practice",
    location: "westham",
    price: 123,
    spaces: 5,
    ratings: 4,
    images: "images/football.jpeg",
  },
  {
    id: 3,
    subject: "BasketBall Training",
    location: "South London",
    price: 80,
    spaces: 5,
    ratings: 3,
    images: "images/basketball.jpeg",
  },
  {
    id: 4,
    subject: "Golf",
    location: "Manchester",
    price: 200,
    spaces: 5,
    ratings: 4,
    images: "images/golf.jpeg",
  },
  {
    id: 5,
    subject: "Cricket ",
    location: "Germany",
    price: 450,
    spaces: 5,
    ratings: 3,
    images: "images/cricket.jpeg",
  },
  {
    id: 6,
    subject: "Coding Practice",
    location: "Dubai",
    price: 225,
    spaces: 5,
    ratings: 5,
    images: "images/ai-vs-machine-learningImage.png",
  },
  {
    id: 7,
    subject: "Film and production",
    location: "westLondon",
    price: 30,
    spaces: 5,
    ratings: 4,
    images: "images/filmandProduction.jpeg",
  },
  {
    id: 8,
    subject: "Music Production",
    location: "Los Angelos",
    price: 320,
    spaces: 5,
    ratings: 3,
    images: "images/music.jpeg",
  },
  {
    id: 9,
    subject: "Marathon Practice ",
    location: "Portugal",
    price: 245,
    spaces: 5,
    ratings: 3,
    images: "images/running.jpeg",
  },
  {
    id: 10,
    subject: "Rugby",
    location: "switzerland",
    price: 700,
    spaces: 5,
    ratings: 4,
    images: "images/rugby.jpeg",
  },
];
